-- Oracle Database DDL Schema Script
-- Software Development Document Environment

CREATE TABLE users (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    phone VARCHAR2(20),
    role VARCHAR2(20) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    account_locked NUMBER(1) DEFAULT 0 NOT NULL,
    failed_attempts NUMBER(10) DEFAULT 0 NOT NULL,
    password_expiry_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE system_config (
    config_key VARCHAR2(100) PRIMARY KEY,
    config_value VARCHAR2(500) NOT NULL,
    description VARCHAR2(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE document_phases (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_number NUMBER(10) NOT NULL UNIQUE,
    phase_name VARCHAR2(100) NOT NULL,
    description VARCHAR2(255)
);

CREATE TABLE document_templates (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name VARCHAR2(100) NOT NULL,
    file_type VARCHAR2(20) NOT NULL,
    file_path VARCHAR2(500) NOT NULL,
    uploaded_by VARCHAR2(50) NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE documents (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id VARCHAR2(50) NOT NULL UNIQUE,
    document_code VARCHAR2(50) NOT NULL,
    app_code VARCHAR2(3) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    description CLOB,
    file_name VARCHAR2(255) NOT NULL,
    file_type VARCHAR2(20) NOT NULL,
    file_path VARCHAR2(500) NOT NULL,
    version_number VARCHAR2(20) NOT NULL,
    phase_number NUMBER(10) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    maker_username VARCHAR2(50) NOT NULL,
    checker_username VARCHAR2(50),
    rejection_reason VARCHAR2(500),
    ai_recommendation CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE audit_trails (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    username VARCHAR2(50) NOT NULL,
    action VARCHAR2(100) NOT NULL,
    details CLOB,
    ip_address VARCHAR2(50)
);
